.TH cheat
.SH NAME
cheat \- generic cheat sheet
.SH Description
.B cheat sheet
is a simple manual containing short hints about commands and shortcuts.

.SH st
.TP
.B Ctrl-Shift-[PageUp]
Zoom In.
.TP
.B Ctrl-Shift-[PageDown]
Zoom Out.
.TP
.B Ctrl-Shift-[Home]
Zoom Reset.
.TP
.B Shift-[PageUp]
Scroll Up.
.TP
.B Shift-[PageDown]
Scroll Down.
.TP
.B Ctrl-Shift-I
Pressing the default binding Ctrl+Shift-i will popup dmenu, asking you to enter a unicode codepoint that will be converted to a glyph and then pushed to st.


.SH dwm
.TP
.B Alt-[Enter]
Open command line interface. In this case it will be st.
.TP
.B Alt-Shift-[j]
Move client to stack.
.TP
.B Alt-Shift-[k]
Move client from stack.
.TP
.B Alt-[-]
Decrease Gap size.
.TP
.B Alt-[+]
Increase Gap size.
.TP
.B Alt-Shift-[+]
Sets Gap size to zero.
.TP
.B Alt-Shift-[i]
Increase the number of clients in master.
.TP
.B Alt-Shift-[d]
Decrease the numberof clients in master.


.SH Surf
.TP
.B tabbed -r 2 surf -e x google.com
Start tabbed surf with Google as home page.
.TP
.B Ctrl-[g]
Opens the URL-bar (requires dmenu installed).
.TP
.B Ctrl-[t]
Display the current TLS certificate in a popup window.
.TP
.B Ctrl-[r]
Reloads the website.
.TP
.B Ctrl-[h]
Change tab.
.TP
.B Ctrl-[l]
Change tab.
.TP
.B Ctrl-Shift-[PageUp]
Zoom In.
.TP
.B Ctrl-Shift-[PageDown]
Zoom Out.
.TP
.B Ctrl-Shift-[Home]
Zoom Reset.
.TP
.B Ctrl-Shift-[r]
Reloads the website without using the cache.

