#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/precmd                                              |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- precmd ---------------------------------------------------------------+

exitcode="$?"
dirsplit=3
# workingdir=" $(pwd | sed 's@'"$HOME"'@~@')"
workingdir="$(pwd | sed 's@'"$HOME"'@~@')"

if [[ ${exitcode} -eq 0 ]]; then
    prompt_symbol_exit="${prompt_symbol_exit_0}"
else
    prompt_symbol_exit="${prompt_symbol_exit_1}"
fi

W=${workingdir}
if [[ $(echo ${W} | grep -o '/' | wc -l) -gt ${dirsplit} ]]; then
    workingdir=$(echo $W | cut -d'/' -f1-$dirsplit | xargs -I{} echo {}"/../${W##*/}")
fi

vcs_info
