#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/precmd                                              |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- precmd ---------------------------------------------------------------+

exitcode="$?"
dirsplit=3

if [[ ${exitcode} -eq 0 ]]; then
    prompt_symbol_exit="${prompt_symbol_exit_0}"
else
    prompt_symbol_exit="${prompt_symbol_exit_1}"
fi

if [[ -w "${PWD}" ]]; then
    prompt_symbol_pwd_writable="${prompt_symbol_pwd_writable_1}"
else
    prompt_symbol_pwd_writable="${prompt_symbol_pwd_writable_0}"
fi

workingdir="${PWD/#$HOME/~}"
workingdir="${workingdir//.config/ }"
workingdir="${workingdir//Desktop/ }"
workingdir="${workingdir//Documents/󱔘 }"
workingdir="${workingdir//Downloads/ }"
workingdir="${workingdir//Music/ }"
workingdir="${workingdir//Notes/󱞂 }"
workingdir="${workingdir//Pictures/ }"
workingdir="${workingdir//Repos/ }"
workingdir="${workingdir//Templates/ }"

W="${workingdir}"
if [[ $(echo ${W} | grep -o '/' | wc -l) -gt ${dirsplit} ]]; then
    workingdir=$(echo $W | cut -d'/' -f1-$dirsplit | xargs -I{} echo {}"/../${W##*/}")
fi

vcs_info
