#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/prompt_rsegment                                     |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- prompt_rsegment -------------------------------------------------------


#    RPROMPT='%F{140}%F{91}%K{140} %T%F{91}%F{255}%K{91} %B${vcs_info_msg_0_}%b%F{53}%F{255}%K{53}${vi_mode_symbol}%F{255} %E'



local LC_ALL="" LC_CTYPE="en_US.UTF-8"
SEGMENT_SEPARATOR=$'\ue0b2'

# Begin a segment
# Takes two arguments, background and foreground. Both can be omitted,
# rendering default background/foreground.
local bg fg
