#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/prompt_workingdir                                   |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- prompt_workingdir -----------------------------------------------------

prompt_workingdir_symbol="${prompt_workingdir_symbol:- }"

prompt_segment green default "${prompt_workingdir_symbol}${workingdir}"
