#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/prompt_userhost                                     |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- prompt_userhost -------------------------------------------------------

prompt_segment black default "${prompt_userhost_symbol} %n@%m" 
