#!/usr/bin/env zsh
#
# +----------------------------------------------------------------------------+
# | ~/config/zsh/functions/zle_keymap_select                                   |
# +----------------------------------------------------------------------------+
# | Copyright © 2021 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# |                                                                            |
# +----------------------------------------------------------------------------+
#
# +----- Variables ------------------------------------------------------------+
prompt_symbol_vimode_nrm="${prompt_symbol_vimode_nrm:-'--NORMAL--'}"
prompt_symbol_vimode_ins="${prompt_symbol_vimode_ins:-'--INSERT--'}"
prompt_symbol_vimode_opp="${prompt_symbol_vimode_opp:-'--OPERAT--'}"
prompt_symbol_vimode_vis="${prompt_symbol_vimode_vis:-'--VISUAL--'}"

# +----- ZLE Keymap Select-----------------------------------------------------+
if [ "${KEYMAP}" = 'vicmd' ]; then
    prompt_symbol_vimode="${prompt_symbol_vimode_nrm}"
fi
if [ "${KEYMAP}" = 'main' ]; then
    prompt_symbol_vimode="${prompt_symbol_vimode_ins}"
fi
if [ "${KEYMAP}" = 'viopp' ]; then
    prompt_symbol_vimode="${prompt_symbol_vimode_opp}"
fi
if [ "${KEYMAP}" = 'visual' ]; then
    prompt_symbol_vimode="${prompt_symbol_vimode_vis}"
fi
zle reset-prompt
